services:
  - type: web
    name: gic-backend
    runtime: node
    region: frankfurt
    branch: main
    rootDir: gic-backend
    buildCommand: npm install && npm run build && printf '\n' | npm run db:push
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: gic-postgres
          property: connectionString
      - key: MEMBER_APP_URL
        value: https://gic-member-static.onrender.com
      - key: ADMIN_APP_URL
        value: https://gic-admin-static.onrender.com
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: FIREBASE_PROJECT_ID
        value: global-impact-church-9b8fd
      - key: JWT_SECRET
        sync: false

  - type: static
    name: gic-member-static
    region: frankfurt
    branch: main
    rootDir: gic-member/gic-member-static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://gic-backend-lx3q.onrender.com
      - key: VITE_FIREBASE_API_KEY
        sync: false
      - key: VITE_FIREBASE_AUTH_DOMAIN
        value: global-impact-church-9b8fd.firebaseapp.com
      - key: VITE_FIREBASE_PROJECT_ID
        value: global-impact-church-9b8fd
      - key: VITE_FIREBASE_STORAGE_BUCKET
        value: global-impact-church-9b8fd.firebasestorage.app
      - key: VITE_FIREBASE_MESSAGING_SENDER_ID
        value: "320455366678"
      - key: VITE_FIREBASE_APP_ID
        value: 1:320455366678:web:b5b41b1528e4df6cf87d37
      - key: VITE_FIREBASE_MEASUREMENT_ID
        value: G-2K8DHP787M
      - key: VITE_FIREBASE_VAPID_KEY
        sync: false

  - type: static
    name: gic-admin-static
    region: frankfurt
    branch: main
    rootDir: gic-admin/gic-admin-static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://gic-backend-lx3q.onrender.com
      - key: VITE_FIREBASE_API_KEY
        sync: false
      - key: VITE_FIREBASE_AUTH_DOMAIN
        value: global-impact-church-9b8fd.firebaseapp.com
      - key: VITE_FIREBASE_PROJECT_ID
        value: global-impact-church-9b8fd
      - key: VITE_FIREBASE_STORAGE_BUCKET
        value: global-impact-church-9b8fd.firebasestorage.app
      - key: VITE_FIREBASE_MESSAGING_SENDER_ID
        value: "320455366678"
      - key: VITE_FIREBASE_APP_ID
        value: 1:320455366678:web:b5b41b1528e4df6cf87d37
      - key: VITE_FIREBASE_MEASUREMENT_ID
        value: G-2K8DHP787M

databases:
  - name: gic-postgres
    region: frankfurt
    plan: starter
    databaseName: gic_db
    user: gic_user
